from pathlib import Path
p=Path('assets/hero/README.md');s=p.read_text(encoding='utf-8')
s=s.replace('Requirements: Node.js, Python only for optional image checks, FFmpeg with palette\nfilters, and Playwright Chromium.', 'Requirements: Node.js, Python with Pillow, FFmpeg with palette filters,\nand Playwright Chromium.')
s=s.replace('npm install\nnpx playwright install chromium', 'npm install\npython -m pip install -r requirements.txt\nnpx playwright install chromium')
s=s.replace('192-color palette, and uses ordered dithering and changed-rectangle optimization.', '192-color palette and uses ordered dithering. `optimize_gif.py` then writes\ntransparent changed rectangles against the fixed global palette and compares\nevery decoded output frame with the original encoded frame. This step is lossless\nrelative to the palette-encoded GIF.')
s=s.replace('by default. The renderer exports', 'by default. `--python /path/to/python` selects a Python interpreter.\n`--reuse-frames` is available for re-encoding only when the source has not changed.\nThe renderer exports')
p.write_text(s,encoding='utf-8')
p=Path('docs/PROFILE_DESIGN.md');s=p.read_text(encoding='utf-8');s=s.replace('# Profile artwork maintenance\n', '# Profile artwork maintenance\n\n## Current AI / QA hero\n\nThe README hero now uses exported GIFs and PNG fallbacks from `assets/hero/`.\nSee `assets/hero/README.md` for the editable source, timeline and export commands.\nOnly image files are embedded in the profile. The source HTML and JavaScript are\nkept for local playback and deterministic rendering. The older SVG hero files\nremain available as alternatives; the instructions below maintain those SVGs,\nproject artwork, the technology board and contribution snake.\n')
p.write_text(s,encoding='utf-8')
p=Path('assets/README.md');s=p.read_text(encoding='utf-8');s=s.replace('# Graphic sources\n', '# Graphic sources\n\nThe active AI / QA hero is maintained in `hero/source/` and exported to GIF/PNG.\nSee `hero/README.md` for rebuilding it. The commands below maintain the retained\nSVG alternatives and the other profile illustrations.\n')
p.write_text(s,encoding='utf-8')
